### PR TITLE
Migrates to Swift 4

### PR DESCRIPTION
**Pull request by sandmman**

### CODE REVIEW

**Comment by troyibm** [comment]
You should remove the need for SwiftyJSON and use Swift 4 Codable.  Or is that the plan after this PR is merged?

**Comment by rolivieri** [comment]
@troyibm Good catch, we will certainly tackle that as part of these changes.

**Comment by troyibm** [comment]
@rolivieri that would be awesome. Thanks.  Also, I was having trouble pushing the kitura-starter to bluemix this weekend.  I was using the `swift-4` branch on https://github.com/sandmman/Kitura-Starter.

**Comment by rolivieri** [comment]
@troyibm We are in the process of installing a new version of the buildpack on bluemix. In the meantine, if you intend to push to bluemix a Swift application that uses Swift 4, you'd need to update the `manifest.yml` file and use the following value for the `buildpack` element: `https://github.com/IBM-Swift/swift-buildpack#develop`.

**Pull request merged**
